### ISSUE TITLE
Add missing mounts for couchbase crt and password file for helm charts

### ISSUE THREAD

**Issue by moabu** [GluuFederation/enterprise-edition#42]
missing 
```
          volumeMounts:
            - name: cb-pass
              mountPath: "/etc/gluu/conf/couchbase_password"
              subPath: couchbase_password
            - name: cb-crt
              mountPath: "/etc/certs/couchbase.crt"
              subPath: couchbase.crt
      volumes:
      - name: cb-pass
        secret:
          secretName: cb-pass
      - name: cb-crt
        secret:
          secretName: cb-crt
```
